### ISSUE TITLE
FAQ

### ISSUE THREAD

**Issue by El-Negroooar** [ht201/swiss-knights-z#14]
- [x] Warum habe ich in der Arena viel stärkere Gegner?
- [x] Wie kann ich die Sterne der Einwohner erhöhen?
- [x] Was bringt der Pitbull-Wachhund für 10 CHF?
- [x] Warum kann meine Zuflucht für 24h angegriffen werden wenn ich ingame bin?
- [x] Wie soll ich Kryptocoins am besten investieren, was macht Sinn?
- [x] Ich habe jemanden auf "Ignorieren" gesetzt, wie kann ich das rückgängig machen?

**Comment by ht201** [comment]
Ich habe die FAQ etwas strukturiert und die Frage der Kryptocoins aus meiner Sicht beantwortet. Bitte mal gegenprüfen.

**Comment by ht201** [comment]
Hoi @El-Negroooar , wenn dieser Task fertig ist, sollte wir ihn schliessen, oder?
Neue FAQ Inhalte befürfen keines Issues, wenn Sie klein genug sind. Issues dienen nur für zeitlich grössere Sachen oder wenn man den Progress tracken möchte.
